### ISSUE TITLE
g.p.o.a.AuditLogListener: Audit plugin unable to process delete event for

### ISSUE THREAD

**Issue by Janitza-AlAt** [grails-plugins/grails-audit-logging-plugin#163]
Grails version: 3.2.10
Plugin Version: 2.0.6

This exception is only when the application is deployed on tomcat
I think the exception is because the enum classes in the domain class like 

class User{
  String name;
  ETitle title
}
public enum ETitle{
  MR, MS;
}
 2018-02-07 13:44:37 ERROR [http-nio-8080-exec-9] g.p.o.a.AuditLogListener: Audit plugin unable to process delete event for User :
java.lang.NullPointerException: null
        at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.initializeCollectionFromCache(DefaultInitializeCollectionEventListener.java:112)
        at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:59)
        at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:2004)
        at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:567)
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:249)
        at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:563)
        at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:132)
        at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:163)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2068)
        at org.codehaus.groovy.runtime.dgm$164.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at grails.plugins.orm.auditable.AuditLogListener.logIds(AuditLogListener.groovy:691)
        at grails.plugins.orm.auditable.AuditLogListener$logIds$5.callCurrent(Unknown Source)
        at grails.plugins.orm.auditable.AuditLogListener.conditionallyMask(AuditLogListener.groovy:679)
        at sun.reflect.GeneratedMethodAccessor630.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
        at grails.plugins.orm.auditable.AuditLogListener$_logChanges_closure10.doCall(AuditLogListener.groovy:632)
        at sun.reflect.GeneratedMethodAccessor974.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at groovy.lang.Closure.call(Closure.java:414)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5226)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2107)
        at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at grails.plugins.orm.auditable.AuditLogListener.logChanges(AuditLogListener.groovy:620)
        at grails.plugins.orm.auditable.AuditLogListener$logChanges$1.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at grails.plugins.orm.auditable.AuditLogListener$logChanges$1.callCurrent(Unknown Source)
        at grails.plugins.orm.auditable.AuditLogListener.onPreDelete(AuditLogListener.groovy:366)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)

**Comment by muser83** [comment]
In `onPreDelete`, the plugin constructs `oldMap` with all persistent properties (`makeMap`), including `hasMany` associations (Hibernate collections)—without protecting them. Unlike the `UPDATE` operation—where `getPersistentValue()` treats associations as "N/A" without accessing them—during `DELETE`, every property (including collections) passes through `conditionallyMaskAndTruncate()` → `truncate()`. With `logIds = true` configured globally, `truncate()` performs `value.each { ... }` on any `Collection` to build the list of IDs; this triggers Hibernate lazy loading which, in the middle of the `PreDeleteEvent` (while the entity is being deleted), fails with a `NullPointerException` (NPE).

A quick fix is ​​to set `nonVerboseDelete = true`. Tested only in version 1.1.3

**Comment by muser83** [comment]
For plugin version 2.0.6 the quick fix should be:

https://github.com/grails-plugins/grails-audit-logging-plugin/issues/153
